### ISSUE TITLE
CheatTable 怎么不见了？

### ISSUE THREAD

**Issue by DGCK81LNN** [DGP-Studio/Snap.Metadata#5]
eed1cfc7c3e79c9550055dcf5000ed14993de603 fix furina fetter story

**Comment by Lightczx** [comment]
不再提供

**Comment by Lightczx** [comment]
> [!WARNING]
> 这些文件已经不再属于我们的生态系统蓝图的一部分

目前只对部分合作开发者开放指定的 API 来访问开发用数据

**Comment by DGCK81LNN** [comment]
好吧，只是看到移除CheatTable的这个commit同时在README里加的列表里还是有CheatTable的

**Comment by Lightczx** [comment]
忘删了，后面写完了再删
